### ISSUE TITLE
Email variable for the review reminder is not being shared with the UI

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#10045]
**Describe the bug**
The email variable `reviewAssignmentUrl` for the template REVIEW_REMIND (review reminder) is not being passed to the UI.

I also think the constants/classes should be renamed to "review reminder".

**To Reproduce**
1. Enter on the review stage.
2. Click on the button to send a reminder to the reviewer.
3. See the variable is not stylized and also doesn't appear in the list of variables.

**What application are you using?**
OJS 3.4

**Additional information**
![image](https://github.com/pkp/pkp-lib/assets/361921/c98fc3dd-5b06-4e25-9262-260743eebeee)

**Comment by jonasraoni** [comment]
Also, it was unexpected for me that the email editor is working differently from the one at the Workflow > Emails, where the variables are displayed in plain text and the icon to insert variables is different:
![image](https://github.com/pkp/pkp-lib/assets/361921/ee3ab134-e505-4df3-80a7-c7cb6a344074)

Assuming it's a work in progress.

**Comment by Vitaliy-1** [comment]
@jonasraoni, is at an old template that should be replaced during upgrade?

**Comment by Vitaliy-1** [comment]
Apart from it, reviewAssignmentUrl isn't exposed deliberately: https://github.com/pkp/pkp-lib/blob/3536404e545ef14ffed6fbe390916d74fc1c875c/controllers/grid/users/reviewer/form/ReviewReminderForm.php#L89

**Comment by Vitaliy-1** [comment]
> Also, it was unexpected for me that the email editor is working differently from the one at the Workflow > Emails, where the variables are displayed in plain text and the icon to insert variables is different

I recall variables are replaced before being sent

**Comment by Vitaliy-1** [comment]
The new wording for the template is different: https://github.com/pkp/ojs/blob/main/locale/en/emails.po#L251
I assume, the old template had custom modifications and that's why it was preserved, right?

**Comment by jonasraoni** [comment]
@Vitaliy-1 this is a mix of UI and backend issue.

The UI of the email editor is different, the email editor that appears when I click on the button `Submission > Workflow > Review > Send Reminder` has:
- `+` button, which allows me to select variables, but only the `URL` is available (it refers to the `{$passwordResetUrl}`.
- The variable is not displayed as text, but as a kind of icon, which looks nice for me, see:
![image](https://github.com/pkp/pkp-lib/assets/361921/eed0768e-89b3-44b7-8e30-064db6c030b2)

On another hand, if I access the email editor of the template, at `Workflow > Emails > Add and edit templates`, then it has:
- `+ Insert content` button
- 32 variables

**Comment by jonasraoni** [comment]
But I also had another issue in this part, I tagged you here:
https://github.com/pkp/pkp-lib/pull/9151/files#r1636973735

I think it might need some extra review, so I just fixed locally by replacing the variable `passwordResetUrl` by `lostPasswordUrl` on the template.

**Comment by asmecher** [comment]
One note about this template that might help clear up some confusion: For any templates that use access keys (3.4.0 and older) or invitations (3.5.0 and newer), we intentionally didn't present the full URL to the editor for viewing. That's because doing so would expose the secret key that goes out with the email. We need to prevent the editor (or anyone else) from intercepting these. Therefore they're coded so that the variable replacement happens right before the message gets delivered.

That said, it would be nicer to show something nicer than `{$someVariableName}` in the interface while editing the email.

**Comment by Tribunal33** [comment]
I think this is already going to be handled but adding an area to check for {$recipientName}.  Copyedit discussion notification for OJS doesn't work but OMP does.

Steps to reproduce.
1. Login as Editor
2. Find submission in copyediting stage.
3. Start a discussion with copyeditor
4. Login as copyeditor
5. Check notification bell
![Image](https://github.com/user-attachments/assets/ca453b21-f2cf-422b-90ba-9c38e79eb93c)

**Comment by asmecher** [comment]
The review assignment URL is intentionally not shared on the UI with the editor. It may contain a one-click review URL, which, if exposed to the editor, would allow them to gain access to the review as reviewer. So that specific variable is a WONTFIX. 

Beau, can you confirm whether all the email variables are replaced when they are sent? If not, that's a high-profile issue that should be fixed for 3.5.0; if they are replaced when they're sent, then we can defer it for later.

**Comment by Tribunal33** [comment]
@Vitaliy-1 is this ready for me?  I'm not seeing any PRs or commits to go with this.  I tried grabbing latest on a 3.5.0 VM but didn't see it fixed.  I still don't see the variable in the optional list nor did I see a rendered variable in the review reminder email template.

<img width="940" height="466" alt="Image" src="https://github.com/user-attachments/assets/5c75c6ee-8b6c-4973-af6b-e3005a20cba3" />

**Comment by Vitaliy-1** [comment]
To summarise:

1. `reviewAssignmentUrl` isn't being replaced in the UI deliberately, doesn't require a fix.
2. tested in 3.5 - `reviewAssignmentUrl` is being replaced in the email with actual URL. This also doesn't require fix
3. In the UI `login to the journal` should be replaced with `reviewAssignmentUrl` placeholder, rather than the link (which doesn't go anywhere as the variable isn't replaced at this stage). 
4. I don't see `emails.reviewRemind.subject` and `emails.reviewRemind.body` localizations for the `REVIEW_REMIND` template. Check if they should be re-added.
5. On the test instance, REVIEW_REMIND template appears in the `email_templates` table rather than `email_templates_default_data`. This might be a mistake and require a fix.
6. Investigate if the issue with inserting email template variables from the UI is specific to the REVIEW_REMIND template. If yes, we can fix it, if not - open a new issue with the description of the problem for a general solution.

Anything else I forgot?
@Hafsa-Naeem, can you take a look at the problem described?

**Comment by Hafsa-Naeem** [comment]
Thanks @Vitaliy-1! the PR is ready to review but I wanted to discuss these two points:
Point 3: the `<a href="{$reviewAssignmentUrl}">login to the journal</a>` is working as expected at send‑time, I've tested the reminder email includes the proper, clickable link. the link only looks broken in the preview editor as variables aren’t being substituted there. But in the actual reminder email, OJS is replacing `{$reviewAssignmentUrl}` with the real URL, so “login to the journal” is working correctly. 
Point 4: Both msgid "emails.reviewRemind.subject" and msgid "emails.reviewRemind.body" are present in locale/en/emails.po. i tested by opening Settings -> Emails -> Review Reminder and the Subject prefilled as "A reminder to please complete your review” and the Body textarea showing your localized HTML, not the raw keys. It’s likely a cached or outdated file. If you still don’t see the strings, let me know and we can dig into the translation/upgrade state.


PR:
OJS(stable-3_5_0): [pkp/pkp-lib Add missing REVIEW_REMIND default data, localization key and UI variable definition #5031](https://github.com/pkp/ojs/pull/5031)

**Comment by Vitaliy-1** [comment]
3. I was meaning that in the UI it should be replaced with a placeholder. Have you seen any examples of this?
4. yes, you are right, see them on the app level: https://github.com/pkp/ojs/blob/59913fb97c0976799724e4c71ba00f454c548fd6/locale/en/emails.po#L246

**Comment by Vitaliy-1** [comment]
Here's an example from the add reviewer form. There's `name` and `review due date` placeholders

<img width="1638" height="324" alt="Image" src="https://github.com/user-attachments/assets/6ce8f7b1-2c5d-4a80-8b91-f6eb3d9a35a5" />

**Comment by Hafsa-Naeem** [comment]
@Vitaliy-1 Ready for review
PR:
OJS(stable-3_5_0): [pkp/pkp-lib Add missing REVIEW_REMIND default data, localization key and UI variable definition #5031](https://github.com/pkp/ojs/pull/5031)
pkp-lib (stable-3_5_0): [pkp/pkp-lib#10045 Fix email preview to show placeholder text instead of unresolved reviewAssignmentUrl link #11728](https://github.com/pkp/pkp-lib/pull/11728)

**Comment by Hafsa-Naeem** [comment]
@Vitaliy-1 Reminder to review, thanks 😇

**Comment by Tribunal33** [comment]
@Hafsa-Naeem when this is merged could you please demo what changes were done. There are a few expected results that were intentionally designed.  I'm a bit lost as to what to validate.

**Comment by Hafsa-Naeem** [comment]
@Vitaliy-1 Rebased and tests are passing. Ready for review
PR:
OJS(stable-3_5_0): [pkp/pkp-lib Add missing REVIEW_REMIND default data, localization key and UI variable definition #5031](https://github.com/pkp/ojs/pull/5031)
pkp-lib (stable-3_5_0): [pkp/pkp-lib#10045 Fix email preview to show placeholder text instead of unresolved reviewAssignmentUrl link #11728](https://github.com/pkp/pkp-lib/pull/11728)

**Comment by Vitaliy-1** [comment]
Thanks @Hafsa-Naeem, I left a comment

**Comment by Hafsa-Naeem** [comment]
@Vitaliy-1 Ready for review
PR:
OJS(stable-3_5_0): [pkp/pkp-lib Add missing REVIEW_REMIND default data, localization key and UI variable definition #5031](https://github.com/pkp/ojs/pull/5031)
pkp-lib (stable-3_5_0): [pkp/pkp-lib#10045 Fix email preview to show placeholder text instead of unresolved reviewAssignmentUrl link #11728](https://github.com/pkp/pkp-lib/pull/11728)
