### ISSUE TITLE
Contributors in browse lists are required to send mail in editorial decision

### ISSUE THREAD

**Issue by diegoabadan** [pkp/pkp-lib#10277]
When there is not at least one author with the option "Include this contributor in browse lists" checked, it is not possible to take most of the editorial decisions regarding a submission. OJS displays the following notification: "There was a problem sending an email message. Please try again later, or contact your system administrator" and does not allow you to proceed.

The names of the authors who would receive the message are displayed on the interface, which makes it difficult to imagine the cause of the error.

I was hoping that this option would not affect the mail sending of the editorial decision. And that the interface agrees with who OJS is actually trying to send the message to.

**To reproduce**
Send a submission with one or more authors in which none of them have this option checked: "Include this contributor in browse lists". Take this submission to the evaluation phase and try to send an editorial decision such as "Request Revisions" or "Decline Submission", keep the option "Send an email notification to the author(s):  _(author(s) name(s)_" checked and try to save the editorial decision.

**What application are you using?**
OJS 3.3.0-18 

**Related forum posts:**
https://forum.pkp.sfu.ca/t/notification-there-was-a-problem-sending-an-email-message-please-try-again-later-or-contact-your-system-administrator/63575/25?u=abadan

https://forum.pkp.sfu.ca/t/what-does-include-this-contributor-in-browse-lists-mean-exactly-when-adding-contributor-metadata-on-submission/33101/5?u=abadan

**Comment by thiagolepidus** [comment]
Hello, I see that removing `true` from the [method that retrieves the authors of the submission](https://github.com/pkp/pkp-lib/blob/stable-3_3_0/controllers/modals/editorDecision/form/EditorDecisionWithEmailForm.inc.php#L216) seems to solve this problem. Does PKP want a PR?

**Comment by asmecher** [comment]
Yes, @thiagolepidus, a PR for that would be welcome, thanks!

**Comment by thiagolepidus** [comment]
PR created: pkp/pkp-lib#10284

**Comment by asmecher** [comment]
Resolved, thanks!

**Comment by tkeil69575** [comment]
While this is a nice little fix for sending out notification emails, it does not consider that if none of the contirbutors are in the browse-list, the email that is sent out has no greeting ... just a not very polite double colon (:).

**Comment by thiagolepidus** [comment]
Hi @tkeil69575,

Although not selected for the browse lists, the contributor is still assigned as a recipient.

We noticed the behavior of displaying a double colon only when the list of contributors is empty. But in this scenario, the email would not be sent because there is no recipient.

If in your scenario there are recipients and the problem still occurs, can you provide a step-by-step where you can reproduce the problem here: https://pkp.sfu.ca/software/ojs/demo/?
