### ISSUE TITLE
OJS - 3.5 - Viewing submission without review stage will display an error when selecting review from side workflow navigation option

### ISSUE THREAD

**Issue by Tribunal33** [pkp/pkp-lib#10626]
**Describe the bug**
When selecting the Review option from the side navigation workflow option within a submission view, that does not have a Review Round created results in an error and greyed out background blocking user.

**To Reproduce**
1. Go to VM of you choice (ex https://jarda.testing.publicknowledgeproject.org/index.php/publicknowledge/en/)
2. Login with any user (admin used for testing)
3. Under Dashboards -> active submissions select a submission without a Review Round
4. Select Rossi -> **View** button
5. Open up dev tools to view console error
6. From the new window pane Select **Review** from side nav Workflow option
7. Observe error in console
**Expected:** No error and pane updates correctly

**Actual:** Pane closes and grey background is unclickable for user.  Error is in the dev tools: 
build.js?v=3.5.0.0:1 TypeError: Cannot read properties of null (reading 'id')
    at Object.getSecondaryItems (build.js?v=3.5.0.0:50:52724)
    at o (build.js?v=3.5.0.0:50:61508)
    at Object.f [as getSecondaryItems] (build.js?v=3.5.0.0:50:62141)
    at build.js?v=3.5.0.0:50:69378
    at xy.fn (build.js?v=3.5.0.0:1:15086)
    at xy.run (build.js?v=3.5.0.0:1:7230)
    at get value (build.js?v=3.5.0.0:1:15308)
    at Qne.get (build.js?v=3.5.0.0:1:10510)
    at build.js?v=3.5.0.0:50:43655
    at o (build.js?v=3.5.0.0:1:23152)

**Additional information**
Please add any screenshots, logs or other information we can use to investigate this bug report.
![Image](https://github.com/user-attachments/assets/079571b1-20ac-4c68-9b52-fa38e18ece78)

**Comment by Tribunal33** [comment]
@jardakotesovec I have updated the local branch and tried again.  The UI no longer crashes with a grey background but an error is still present due to null object.  Will add another screenshot for reference.

Additionally, the there are added steps since the default already has the review option highlight you will first need to select another option and then back to the Review option.

I will lower the severity as well.

**Comment by taslangraham** [comment]
@jardakotesovec I added a fix for this. Please take a look. 
**PRs**
https://github.com/pkp/ui-library/pull/453

**submodule updates**
https://github.com/pkp/ojs/pull/4534
https://github.com/pkp/ops/pull/820
https://github.com/pkp/omp/pull/1778

**Comment by jardakotesovec** [comment]
@taslangraham I think this is already addressed on main branch..  as part of some other recent changes..  Overall still refining that area.. so was asking @Tribunal33 to hold with other reports until its ready for testing..

@Tribunal33 Can you confirm it?

**Comment by jardakotesovec** [comment]
Or maybe it its not.. but in anycase thats with me :-)

**Comment by taslangraham** [comment]
@jardakotesovec I'll close out those PRs then

**Comment by Tribunal33** [comment]
@jardakotesovec let me know once it is merged.  I tried pulling locally and I'm still seeing the error but not sure if that was a me thing or not.

**Comment by Tribunal33** [comment]
This bug no longer is reproducible.  It has been fixed on the latest changes to UI-library.  Closing the bug.
