### ISSUE TITLE
[OMP Dois] | DOI management - books published already in copyediting stage do not show up in the DOI page

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#11893]
### Valid Title

- [x] I have updated the title to accurately reflect the bug description

### Description

OMP allows books to be published already during the Copyediting stage.

However, if a book is published in copyediting, it does not seem to appear on the DOI management page.

### Steps to Reproduce

1. Login with User/Role editor
2. Navigate to Submissions > any book in copyediting
3. Publish the book during copyediting stage
4. Navigate to DOI management page and see the book missing

### Expected Result

Allow DOI management for all published books

### Actual Result

Does not allow DOI management for published books still in copyediting. See below the book published by Locke missing from the list.

<img width="1017" height="400" alt="Image" src="https://github.com/user-attachments/assets/556b7442-6065-457c-b362-fa3d633e3d03" />

<img width="714" height="257" alt="Image" src="https://github.com/user-attachments/assets/dd3f3f1d-762a-4251-84ca-e56548bf4436" />

### Application Version

OMP 3.4, also current main branch

<hr>

PRs:
stable-3_4_0: https://github.com/pkp/omp/pull/2140
stable-3_5_0: https://github.com/pkp/omp/pull/2146
main: https://github.com/pkp/omp/pull/2145

**Comment by Tribunal33** [comment]
@ajnyga Can you find out what settings are displayed here.  I believe it is working correctly and this isn't a bug.  Try with a new submission.  Old submissions that have been in copyediting stage after putting in the correct DOI prefix might not be affected.  I think @bozana taught me something about that in #10553 .

DOI management settings that need to be turned on are:

<img width="756" height="299" alt="Image" src="https://github.com/user-attachments/assets/705e8223-e39d-4f3b-ba74-a6611c33e10c" />

<img width="347" height="198" alt="Image" src="https://github.com/user-attachments/assets/66f7f42a-ee93-4af1-819a-6d52013a4eea" />

Then individual chapter settings that need to be enabled are :

<img width="685" height="90" alt="Image" src="https://github.com/user-attachments/assets/2b7ebeaa-98aa-4063-932d-3cad40f9cae6" />

Here is the results of each chapter getting it's own DOI both on the main page and the individual chapter page.

<img width="614" height="436" alt="Image" src="https://github.com/user-attachments/assets/28334be8-0481-4fe4-8c6a-5f9f360bf890" />

And DOI page looks like this....

<img width="735" height="439" alt="Image" src="https://github.com/user-attachments/assets/e2f35bf8-7787-4039-9371-262a00b6a34e" />

**Comment by Tribunal33** [comment]
@ajnyga sorry you can ignore my last message your original problem has nothing to do with chapters.  I don't know what I was thinking.  However, this issue should be resolved here: https://github.com/pkp/pkp-lib/issues/11887.  Closing this as a duplicate even though it is OMP specific.  I checked this on 3.5 and it doesn't work either so not sure when it used to work. 

Update: If you start a new submission rather than publishing an existing one I think it will show up in the DOI page.  I tested it on 3.4 and 3.5 and it works.  Taking a submission that was existing in copyediting stage after setting up the DOIs did not work.

**Comment by ajnyga** [comment]
Hi,

Thanks. I am not using the automatic DOI assignment. That is turned off in purpose. 

I tested this with an existing submission so maybe it affects just those.

**Comment by bozana** [comment]
Hi @Tribunal33, I could reproduce it in 3.4 -- if a new submission is published when it reaches the copyediting stage, the submission is not listed on the DOI management page. We consider only submissions that are in the production stage for the listing. Because this happens only in OMP in earlier versions 3.4 and 3.5, maybe to leave this issue, so it can be assigned to 3.4.0.10. The other issue is only for 3.6, where we can publish a submission from any worflow stage, so there a slightly different fix is needed.
In OJS 3.4 -- that also allows publishing in the copyediting stage, the copyediting stage was considered, so no need to change anything there.

**Comment by bozana** [comment]
@ewhanson, could you please review the PR above?

**Comment by ewhanson** [comment]
Thanks @bozana. The change looks good but all the tests are still failing, though it seems unrelated.

**Comment by bozana** [comment]
Hi @Tribunal33, all merged, so if you would like to double check it and then close the issue...
Thanks a lot!

**Comment by Tribunal33** [comment]
Thanks @bozana this is working as expected now. I have tried on OJS, OMP, OPS 3.4, 3.5, main some with versioning. And they are all passing now. When I reach the Copyediting stage it is now correctly being placed in the DOI management table.  To double verify, also, the number of submissions that are in the copyediting, production or published state add up to the number of entries in the DOI management table.  This acts as a second check.  Looks great now.  @ajnyga I'm closing now but please verify my understanding is correct.

<img width="1590" height="621" alt="Image" src="https://github.com/user-attachments/assets/39245e60-9b1f-4320-9ad6-e6afbaf9446e" />

**Comment by ajnyga** [comment]
Hi, this looks now what I would expect, thanks!
