### ISSUE TITLE
[Frascati] | Submission workflow - Publication > Metadata, Frascati list is not persisting after article is published

### ISSUE THREAD

**Issue by Tribunal33** [pkp/pkp-lib#11964]
### Valid Title

- [x] I have updated the title to accurately reflect the bug description

### Description

Similar to this issue here #11481.  Not sure if this was a result of being changed from Keywords field to the Subjects field.  When you select Frascati controlled vocab options from the list it should populate the Subject field.  After publication these enabled vocab options should maintain their checked off status and be displayed in the Subject field. 

Potentially a more general fix could be applied for this new field for publication data object here #11557

### Steps to Reproduce

1. Precondition: Must have Frascati plugin installed.
2. Login with Author (or any role that can create a submission)
3. Create a new submission
4. When the Frascati section appears select the button `Add Frascati Subjects` and select a few (remember them).
5. Continue with submitting the submission (details don't matter)
6. Navigate to the submission
7. Continue with the submission process until it is published.
8. Navigate back to that submission and select the Publication > Metadata 
9. Select the `Add Frascati Subjects` button 

### Expected Result

The Frascati Subjects that were selected during the submission process should remain checked off.  The Subject field should also have them

### Actual Result

The Frascati Subjects are not checked and the field is missing the Frascati subjects that were selected during the submission workflow.

### Application Version

OJS 3.6

### Additional Information

https://github.com/user-attachments/assets/23a18668-472d-4d6e-8425-7ede4134bfd5

### Possible Solution
Should be resolved via https://github.com/pkp/pkp-lib/issues/11557

**Comment by Tribunal33** [comment]
Realised to you can simplify the steps to just unpublish a current submission add Frascati subjects and then republish.

**Comment by touhidurabir** [comment]
Hi @Tribunal33 this is ready for QA now that we have merged the PRs from https://github.com/pkp/pkp-lib/issues/11557 . I would suggest to consider the cases of https://github.com/pkp/pkp-lib/issues/11481 to test with .

**Comment by Tribunal33** [comment]
@touhidurabir.  The bug is fixed but I'm noticing that I'm not getting the auto complete anymore for frascati keywords.  I can see the auto complete for subjects already entered but not for other ones.  "Mathematics" for example.  When I enter it exactly as in the form it is not being picked up in the list.  Not sure if this was a change from previous keyword field to subject field but doesn't feel as integrated as it did before.

<img width="1435" height="200" alt="Image" src="https://github.com/user-attachments/assets/ac166fa4-1018-46ff-aa2d-4a1ef418f679" />

I also checked #11481 and I can see that it is passing.  The database records do not revert when saving keywords again.   It tried it a few times and followed the same steps in 11481.  It correctly kept the records in tact.

<img width="1258" height="600" alt="Image" src="https://github.com/user-attachments/assets/9a60013a-0b2f-4675-9ed0-f7e78a7ac47a" />

**Comment by touhidurabir** [comment]
> I'm noticing that I'm not getting the auto complete anymore for frascati keywords. I can see the auto complete for subjects already entered but not for other ones.

@Tribunal33 do you mean that frascati only works for `subjects` meta field and not for others like `keywords` ? if so , I think that is expected as frascati only targeted to work with subject . Or is something different ?

**Comment by Tribunal33** [comment]
@touhidurabir sorry but not exactly.  I'm saying that when I enter a frascati subject into the field there is no auto complete suggestion.  Nor is there any way to enter a frascati keyword directly into the field you have to go through the subject form and tick off a check box. 

Here is what a frascati suggestion would look like.  This only works after I have already selected one from the form but it doesn't auto suggest any others that haven't been selected.  Like Mathematics.  It used to auto suggest these frascati options and if you selected it then it would reflect in the list as being checked.

<img width="304" height="247" alt="Image" src="https://github.com/user-attachments/assets/65bd7436-e60a-4ed7-970a-055c7091223a" />

**Comment by touhidurabir** [comment]
@Tribunal33 still not sure what is the problem here but for me it looks like below 

<img width="2676" height="666" alt="Image" src="https://github.com/user-attachments/assets/056bab86-836d-4b92-b348-7e53c250dd04" />

I haven't selected any thing from the list and just using as it is and seems auto suggestion does work me . Sorry if I am misunderstanding something here .

**Comment by Tribunal33** [comment]
My appologies @touhidurabir I'm not sure what went wrong with mine, but it is working now.  I can see the auto-suggest, I can select the auto-suggest and it is showing the entry ticked correctly.  This passes QA.
