### ISSUE TITLE
improve pub id assignment

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#4132]
The way pub ids (DOIs, URNs) are assigned to objects should be improved so that it is more user friendly. The concept is coming:

**Comment by NateWr** [comment]
After some discussion, we came up with the following workflow. The assumptions of this workflow are:

- Most users will accept the automatically generated DOI. But in some cases they want to be able to change it before publication.
- DOIs should not be changeable after publication. If they need to be changed, a separate admin- or JM-level tool needs to be used.
- Publication will often kick off an automatic deposit process. The user should be informed of this and prevented from making changes once the deposit process has been initiated.

### Before submission is scheduled for publication
![doi-before-schedule](https://user-images.githubusercontent.com/2306629/46798612-590b8000-cd4a-11e8-87f4-eacfdefc6431.png)

### When the submission is scheduled for publication but not yet published
![doi-before-publish](https://user-images.githubusercontent.com/2306629/46798871-0f6f6500-cd4b-11e8-91a0-325486c2d166.png)

### When the submission is published and automatic deposit exists
![doi-auto-assign](https://user-images.githubusercontent.com/2306629/46798966-62e1b300-cd4b-11e8-9dcf-8efbbdfe9ed5.png)

### When the submission is published and automatic deposit is disabled
![doi-manual-deposit](https://user-images.githubusercontent.com/2306629/46799111-cd92ee80-cd4b-11e8-9f22-fd65ce21b5f0.png)

### When the deposit process has been initiated but not yet finished
![doi-await-confirm](https://user-images.githubusercontent.com/2306629/46799182-03d06e00-cd4c-11e8-9fc6-a3d13deb6f8f.png)

### When the deposit process has completed successfully
![doi-confirmed](https://user-images.githubusercontent.com/2306629/46799245-2febef00-cd4c-11e8-8c91-689651e1ed4f.png)

What happens when the deposit process fails? Can the user retry from the deposit grid? If so, let's show a status message with a link to that. If not, what other advice can be provide about a next step??

### When automatic assignment is disabled
In some cases, journals do not want to have a DOI automatically assigned. In such cases, the user can turn auto-assignment off from the plugin settings area, and the following would appear during the workflow:
![doi-no-auto-assign](https://user-images.githubusercontent.com/2306629/46799591-113a2800-cd4d-11e8-8044-e35b17951126.png)


@jmacgreg @AhemNason @ajnyga Any thoughts on this? Can someone also check the language of the status messages to ensure they make sense?

**Comment by bozana** [comment]
Maybe to mention, that there will be a new setting in the DO/URN plugin settings: a pre-selected checkbox "Automatically assign DOIs". If the journal deselects it, the scenario "When automatic assignment is disabled" applies.
We would also provide a drop-down in the DOI plugin settings to chose the registration agency, so that we know how to read the deposit status that will be displayed here in the identifier tab.
The save button would be used to save the eventual changes on the DOI and this would be a point to check a few things we can, if the DOI is correct (e.g. prefix and uniqueness)?
Note: we currently do not support URN registration/deposit -- it is national library dependent -- so we cannot display the statuses correctly for URNs.

**Comment by ajnyga** [comment]
Really like the status and the general ideas here 👍 

Questions:
1. If the system is automatically assigning DOIs for all articles, how do you remove a DOI from a specific article? For example the journal might have a "news" section and do not want to have DOIs for content in that section (DOIs cost money).

2. Are we letting editors manually edit the DOI, both the prefix and the suffix? If yes, we need to carefully check that no collisions happen and that the DOI is still valid. In general I am not sure if letting editors to manually edit the DOI is a good idea. DOIs are not meant to be human readable, so I do not see the actual need? What are the use cases here?

3. Does the system still suggest DOI assignment when you choose "Schedule for publication"  when the automatic assignment is disabled?

4. In general I think it would make sense to remove the unresolvable parts from the DOI suffix altogether. I think this is a good example of a situation where those parts make using DOIs complicated and there is really nothing gained with using things like issue volume or number as part of the DOI suffix. (see https://github.com/pkp/pkp-lib/issues/4056 for other arguments, bottom line: the suffix should be something that can be generated right away when the submission is made)

**Comment by ajnyga** [comment]
An addition above: for future work it would be a good idea if you could assign and deposit an article DOI before the issue it is attached to is published. This would also add support for publishing without issues.

**Comment by NateWr** [comment]
> If the system is automatically assigning DOIs for all articles, how do you remove a DOI from a specific article? For example the journal might have a "news" section and do not want to have DOIs for content in that section (DOIs cost money).

Maybe they should use the Announcements instead! :) I don't know about this use case, but it doesn't seem hard to address when the need arises.

> Are we letting editors manually edit the DOI, both the prefix and the suffix? If yes, we need to carefully check that no collisions happen and that the DOI is still valid. In general I am not sure if letting editors to manually edit the DOI is a good idea. DOIs are not meant to be human readable, so I do not see the actual need? What are the use cases here?

When a DOI is saved it should be validated. The use cases? I agree with you but my understanding is that editors are adamant they want to edit DOIs. Maybe there are issues with importing back-catalogues. I'm told the use case exists.

> In general I think it would make sense to remove the unresolvable parts from the DOI suffix altogether.

I agree, but again I think it's a common request. :/

**Comment by NateWr** [comment]
>  for future work it would be a good idea if you could assign and deposit an article DOI before the issue it is attached to is published. This would also add support for publishing without issues.

DOI deposit should be kicked off when the article is published. To support continual publishing, we need to ensure a "publication event" happens that is common to both modes of publishing. We'll need that for email notifications, submission tracking, activity logs and other things in the system.

**Comment by ajnyga** [comment]
> DOI deposit should be kicked off when the article is published. To support continual publishing, we need to ensure a "publication event" happens that is common to both modes of publishing. We'll need that for email notifications, submission tracking, activity logs and other things in the system.

Agree, but with the current default DOI pattern this is not possible (free the DOI and remove issue metadata from the suffix pattern! 🤣 )

**Comment by bozana** [comment]
> 
> 
> > DOI deposit should be kicked off when the article is published. To support continual publishing, we need to ensure a "publication event" happens that is common to both modes of publishing. We'll need that for email notifications, submission tracking, activity logs and other things in the system.
> 
> Agree, but with the current default DOI pattern this is not possible (free the DOI and remove issue metadata from the suffix pattern! rofl )

The journal can free its DOIs by defining its own pattern for article DOIs in DOI plugin settings, that does not contain the volume, issue or something else....

**Comment by ajnyga** [comment]
> The journal can free its DOIs by defining its own pattern for article DOIs in DOI plugin settings, that does not contain the volume, issue or something else....

Sure they can. But as long as OJS supports things like volume number variable in the DOI suffix, the system needs to support that. 

This makes things overly complicated and the only thing that is gained is that the volume number is visible in the DOI. That is really all, a visual thing. A good example how things get complicated is DOI support in quicksubmit plugin: https://github.com/pkp/quickSubmit/pull/20.

If we just remove the issue related variables it would solve this. We would only provide suffix variables that are available from the beginning of the submission process.

Yes, it would probably be a surprise for journals using those variables, but I bet that many would not even notice if they just use the default pattern. Some would of course.

But this is probably the wrong place to argue this issue and I have really given all the arguments for this case.

**Comment by bozana** [comment]
I believe the solution to explicitly, and not automatically, assign DOIs in OJS 3 was right -- that way we are producing less errors, support cases and further requirements. Thus I would rather leave this as it is now in OJS 3 i.e. no automatic assignment.

The unresolvable patterns in the suffix seem to be a problem i.e. a source of confusion. For that, we could:
1) only allow the object ids to be used in the patterns (so that they are always resolvable), as @ajnyga said. Knowing the earlier wishes and requirements from the users, there is a significant amount of users wishing their DOIs to look differently and use all kind of patterns, e.g. the URL custom identifiers, that might not be resolvable immediately.
2) change the current default patterns so that they do not contain %v and %i. In this case we could update the current journals using default patterns to use custom patterns (that would be equivalent to the current default patterns), but the new journals that would choose to use the default pattern (which apparently lots of them do) would not have this problem.
Additionally we could add those status messages and explanations, that @NateWr proposed above. I think they would help in any case.

A further problem and source of confusion seems to be that the user maybe do not know that they have to register a DOI, before using it publicly. The status messages and explanations, from above, would help here as well, I believe.

**Comment by ajnyga** [comment]
The DOI pattern without the issue data is not a goal itself. But with the kind of DOI pattern I suggested OJS could handle different kinds of publishing more easily. I am seeing four kinds of publishing modes that could be supported:
1. Publishing full issues
2. Publishing single articles
3. Publishing single articles that are attached to an issue later (forthcoming articles)
4. preprints (yes, I know about the plan to make a separate preprint server, but it would be very easy to enable OJS journals to publish preprints using OJS)

I think the DOI registration process in OJS should work so that it supports all those modes of publishing.

**Comment by ajnyga** [comment]
One more thing comes to mind in the process:
When the article metadata is changed, especially now with versioning, should there be an easy way of upgrading the metadata attached to a specific DOI. Crossref surely would like to receive the changed metadata and currently the changes made after the registration of the DOI are not visible unless the editor manually registers the DOI again.

**Comment by ajnyga** [comment]
I agree that everything should not be handled and solved here. The DOI pattern already has an issue I referenced above. But I do think that the problem with the pattern and the time-gap are something that should be kept in mind when this workflow is planned so that we do not need the redesign it again. The other thing is versioning, does the workflow above work with the new versioning feature?

The whole process of assigning and registering DOIs would get a lot simpler if the DOI would be registered when the article is published (by itself or as part of an issue). I think this would make sense to most editors. This would also give some clear answers to the questions you listed above in the use case and would be one form of automation.

I also still emphasize that changes in article metadata should be exported to crossref/datacite as well somehow. I do believe that Crossref expects this to happen, they want to have the latest version of article metadata.

I am not against automation (on the contrary) as long as you can still remove a DOI form an article if needed. I see this an as extension of the ability to edit the DOI. 

I also agree that editors are not that interested in DOI patterns. We now have 40 journals using DOIs and I tell them to use the `initials.submission_id` suffix. I have not come across an editor who even asks why. Not saying that the cases Bozana referred to do not exist. 

With back issues and DOI validation we need to remember that a journal may have several prefixes and different patterns for older suffixes. I mean they might have some old content with one prefix and have a new prefix in the platform they are currently using. We have a couple of these cases.

The automation could be tied to the editorial workflow. The back issues are usually imported using the XML import or the quicksubmit plugin. You could have an optional DOI assignment in quicksubmit and the ability to add a DOI to the imported XML (not sure if you already have?).

**Comment by bozana** [comment]
Regarding the automatic DOI assignment, I can only speak from my experience with OJS 2: 
-- we definitely then need an "exclude" options: to exclude the current object as well as all underlying/belonging objects, e.g. to exclude all objects (articles and galleys/files) of an issue.
-- the problem with import: we did not have a good possibility to solve the problem when the back issues (issues and articles imported via XML) should be excluded from assigning them the DOI -- there would have to be an XML element/attribute that would define the exclusions and this I can imagine is something that the user do not think about at all, which would probably again lead to the unwanted DOI assignments and the consequences of that. And because we assign the DOI automatically, i.e. when a user is viewing/reading a published object (e.g. article), everything not defined as "excluded" will get a DOI. Is there a good solution for this you can think of?
It would be great to hear what @jmacgreg and @AhemNason think about that -- they have lots of experience with users...

Regarding versioning: this is a huge topic we still have to solve :-( We would need to see how different agencies deal with versions, assigning DOI to different versions and registering them, and think of a good solution for OJS, eventually considering even different solutions for different agencies :-(
So I cannot tell anything about that now :-(

**Comment by NateWr** [comment]
Maybe we should have a call to talk through the import stuff. And yes, I'd like to hear from james and mike. It seems like this is something we control on our end, so should be able to work around any problems. But maybe I am misunderstanding something.

**Comment by AhemNason** [comment]
I think we're on the right track here for sure. I have a few opinions about what makes sense here. One is that editors do sometimes want to change their DOIs and not really for "vanity DOI" reasons so much as "this journal still exists in print and they want to make sure the print version has the intended DOI in it". This isn't super common but it should be ok to have custom DOIs. 

I think one thing that would really help is a confirmation modal when you publish. I see lots of heads up on the articles themselves but I think it would be nice if, as you publish, you're asked to confirm the minting and submission of the DOIs at that point. That way, if someone forgets to go back and modify a DOI between the time it's accepted and published, there's one last time to say "hey, these are what the DOIs are going to be, you're sure you want to mint them and register them? this is the last chance". 

One of the most common issues we run into is someone publishes an issue without the right issue metadata in it, so we end up with auto-generated DOIs that look like this: 

``10.whatever/abbrev.2018.v0.i0.articleid``

I think there are two ways around this:

1. There's a metadata sanity check that won't populate that part of the pattern if the field is still on the default. 
2. We scrap the "volume" and "issue" entirely and just make the default pattern ``abbrev.year.articleid``. 

Crossref's own criteria are pretty flexible (https://support.crossref.org/hc/en-us/articles/214669823-Constructing-your-identifiers) , but probably the biggest reason people end up with Conflicts is that they register these v0.i0 DOIs, they're submitted automatically (because they published the issue BEFORE adding the articles to it [and didn't fix their metadata]), and they fix them and re-submit. 

If an issue is already published, then the language above makes sense. "This will be the DOI moving forward and you won't be able to change it" and maybe even an "are you sure".

**Comment by NateWr** [comment]
> it would be nice if, as you publish, you're asked to confirm the minting and submission of the DOIs at that point

I have some plans for better managing and presenting pre-publish overview/confirmation/requirements. In the meantime, @bozana, maybe you can check if the scheduled task to automatically mint DOIs is "on" and, if so, present something in the publish modal?

**Comment by ajnyga** [comment]
Just a brief comment to the suggested `abbrev.year.articleid` pattern. I would still leave the year out. You do not know the publishing year for the article when the first manuscript arrives to the journal. By leaving the year out and just sticking with `abbrev.articleid` you know the DOI of the article right away when the first submission is made. This creates transparency to the way DOIs are created.

**Comment by NateWr** [comment]
Going to close this as obsolete. The DOI assignment UI is being reconsidered separately from the submission workflow.
