### ISSUE TITLE
Unable to sent email to the assigned reviewer

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#7058]
**Describe the bug**
Fatal error occurs when pressing Email Reviewer button on the review stage under assigned reviewer.
```
27.0.0.1:39560 [500]: GET /index.php/psp/$$$call$$$/grid/users/reviewer/reviewer-grid/send-email?submissionId=106&reviewAssignmentId=172&stageId=3&round=0&_=1620913155202 - Declaration of EmailReviewerForm::execute($submission) must be compatible with PKP\form\Form::execute(...$functionArgs) in /home/doc/OJS/development/ojs/lib/pkp/controllers/grid/users/reviewer/form/EmailReviewerForm.inc.php on line 87
```

**To Reproduce**
1. Make a submission and forward it to the review stage
2. Assign a reviewer
3. Press Email Reviewer button under the reviewer
4. See error.

**What application are you using?**
 OJS master branch

**Additional information**
When assigning reviewer another error occurs related to the duplicated `use` statement for the same class:
```
127.0.0.1:39000 [500]: GET /index.php/psp/$$$call$$$/grid/users/reviewer/reviewer-grid/show-reviewer-form?submissionId=106&stageId=3&reviewRoundId=117&selectionType=1&_=1620913155190 - Cannot use APP\template\TemplateManager as TemplateManager because the name is already in use in /home/doc/OJS/development/ojs/lib/pkp/controllers/grid/users/reviewer/form/ReviewerForm.inc.php on line 19
```

**Comment by asmecher** [comment]
@Vitaliy-1, I already fixed the ReviewerForm issue this morning; I think the "must be compatible" statement is just a warning. Can you see if it's still broken?

**Comment by Vitaliy-1** [comment]
Still receiving this; it's a fatal error:
```
PHP Fatal error:  Declaration of EmailReviewerForm::execute($submission) must be compatible with PKP\form\Form::execute(...$functionArgs) in /home/doc/OJS/development/ojs/lib/pkp/controllers/grid/users/reviewer/form/EmailReviewerForm.inc.php on line 87
```

**Comment by asmecher** [comment]
@Vitaliy-1, are you using PHP8? I think this is a preexisting problem that was promoted from a warning to a fatal error only recently. You might see others like this. In any case, https://github.com/pkp/pkp-lib/commit/5c16d28b5bf938e018799285d1039a93c49913bf should fix it.

**Comment by mrqorib** [comment]
Hi @asmecher , the commit didn't fix the error for me, but it produces a different error message instead
```PHP Fatal error:  Declaration of EmailReviewerForm::execute($submission, ...$functionArgs) must be compatible with Form::execute(...$functionArgs) in /home/cljournal/subs2.cljournal.org/lib/pkp/controllers/grid/users/reviewer/form/EmailReviewerForm.inc.php on line 72```

**Comment by mrqorib** [comment]
I found this PR #8045 instead, and it works. Thanks!

**Comment by Vitaliy-1** [comment]
Already fixed
