### ISSUE TITLE
Issues with the NativeImportExportPlugin

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#7190]
**Describe the bug**
I've had some issues while trying to import a set of XML files into OMP through the CLI interface.

**PRs**
`stable-3_3_0`
- https://github.com/pkp/pkp-lib/pull/7201
- https://github.com/pkp/ojs/pull/3414
- https://github.com/pkp/omp/pull/994
- https://github.com/pkp/ops/pull/287

`main`
- https://github.com/pkp/pkp-lib/pull/7952
- https://github.com/pkp/ojs/pull/3413
- https://github.com/pkp/omp/pull/1130
- https://github.com/pkp/ops/pull/286

****
**Issues that affect OJS and OMP**
- [x] Invalid `filterConfig.xml` configuration leads to failure when retrieving the parsed objects.
- [x] The code isn't reporting the [DTD validation errors](https://github.com/pkp/omp/blob/stable-3_3_0/plugins/importexport/native/NativeImportExportPlugin.inc.php#L352).
- [x] The underlying code expects the request to have a context and a user, so there are several failures related to `Request::getContext()` and `Request::getUser()` when running through the CLI.
- [x] A zeroed `direct_sales_price` (e.g. `direct_sales_price="0"`) is causing unexpected issues due a [forgiving filter](https://github.com/pkp/pkp-lib/blob/stable-3_3_0/plugins/importexport/native/filter/NativeXmlSubmissionFileFilter.inc.php#L130).
- [x] [Accessing a possibly non-declared variable](https://github.com/pkp/pkp-lib/blob/stable-3_3_0/plugins/importexport/native/filter/NativeXmlSubmissionFileFilter.inc.php#L323) causes an issue.

**Issues that affect only OMP**
- [x] The code is using the `file_id` as if it was a `submission_file_id` in [some places](https://github.com/pkp/omp/blob/stable-3_3_0/plugins/importexport/native/filter/NativeXmlPublicationFormatFilter.inc.php#L105), so we'll end up with data being overwritten unexpectedly whenever the auto incremental IDs go out of sync.
- [x] The [wrong ID is being used to connect a chapter to a submission file](https://github.com/pkp/omp/blob/stable-3_3_0/plugins/importexport/native/filter/NativeXmlChapterFilter.inc.php#L146), it may "work" and cause unexpected behavior.
- [x] The method [`setAssocId()`](https://github.com/pkp/omp/blob/stable-3_3_0/plugins/importexport/native/filter/NativeXmlPublicationFormatFilter.inc.php#L107) doesn't exist (affects only `stable-3_3_0`).
- [x] The code isn't updating the [publication's cover image](https://github.com/pkp/pkp-lib/blob/stable-3_3_0/plugins/importexport/native/filter/NativeXmlPKPPublicationFilter.inc.php#L100) (affects only `stable-3_3_0`)

Other issues I had have already been addressed by recent PRs.

~~**Improvements**~~
~~The improvements below won't be handled due to our preference for API integrations.~~

~~1. Generate the `.xsd` file on-the-fly to validate dynamic options (e.g. invalid `user_group_ref`)~~

~~2. The process may fail due to memory exhaustion~~
~~Fix: I just used `ini_set` with a high memory limit. As we're not using transactions, some trash may be left if the process is interrupted unexpectedly, so follow some notes:~~
~~- Detect and fix what's causing the high memory usage. I'd say it's the base64_decode, then we could try to find a library that process it in chunks, so we can save the data in a temporary location.~~
~~- If fixing is too complex, then I think it would be reasonably good to warn/force the user to specify a high memory limit (or to increase the memory limit programmatically when it's going down)~~

~~3. I think the user group name (and any other similar data) can be located in a case-insensitive way
Location: https://github.com/pkp/pkp-lib/blob/stable-3_3_0/plugins/importexport/native/filter/NativeXmlPKPAuthorFilter.inc.php#L80 and https://github.com/pkp/pkp-lib/blob/stable-3_3_0/plugins/importexport/native/filter/NativeXmlPKPAuthorFilter.inc.php#L84~~

**What application are you using?**
OMP 3.3.0

**Comment by NateWr** [comment]
@jonasraoni with (1) have you confirmed that it is actually the `file_id` property and not the `submission_file_id`? The distinction was only added in 3.3, and in several places code still refers to `fileId` when it is actually using `submissionFileId`.

**Comment by jonasraoni** [comment]
Yeah, I've inspected what was happening and the code ended up updating older submissions instead of the one being imported. My fix solved the problem, but I didn't spend much time inspecting the internals, perhaps the code should be using the submission_file_id instead of the file_id.

**Comment by asmecher** [comment]
@jonasraoni, I'm assigning this to @defstat for a look, but if any of these items have already been fixed through your own exploration, could you open a PR for his review?

**Comment by jonasraoni** [comment]
@asmecher Some of the fixes I've added are ok to be merged already, but others will require a better investigation to avoid fixing symptoms instead of causes. Anyway, I can create a draft PR to discuss :)

**Comment by jonasraoni** [comment]
Also, it would be great to have extra validations. For example an invalid ID at the `monograph->current_publication_id`, allows the process to continue, everything seems to work fine, but in the end, the submission isn't accessible because it's linked against a publication ID that doesn't exist ([#6093](https://github.com/pkp/pkp-lib/issues/6093) will address this somehow).

As it must be happening in other places (I think I also flagged it in the author ID), it would be interesting to enclose the process in a transaction (and keep track of inserted files to remove them later in case of failures).

**Comment by jonasraoni** [comment]
I've created these PRs against `stable-3_3_0` to handle the issues I've mentioned before:
OMP: https://github.com/pkp/omp/pull/994
PKP-LIB: https://github.com/pkp/pkp-lib/pull/7201

Let me know if I should attempt to decrease the memory usage: I think the easiest way would be to rewrite the `.xml` file with a SAX parser and replace the base64 encoded content by a <href> element pointing to a temporary file, then a similar process should be done for the export (just to avoid having a huge DOMDocument on the memory).

I also flagged other things, that I didn't attempt to fix:
- Not validated inputs: e.g. I can use `openAccessXXX` as a value for the `sales_type`
- Maybe there are required fields not being validated: e.g. perhaps the `locale` attribute in the `<monograph>` element should be required, as not filling it raises an issue in another part of the code.

**Comment by jonasraoni** [comment]
I've addressed other issues in the PR:
- Fixed another bug related with linkage, this time between the chapter and the submission file (it was using the `file_id` instead of the `submission_file_id`, so data ended up scrambled)
- Moved locale field from the publication to the submission level
- Added a warning when using an inexistent author ID

**Comment by ajnyga** [comment]
Hi @jonasraoni 
Thanks for fixing some issues here. I am working on importing around 500 books to OMP so these are very important.

What I am seeing is that there is no way of importing a submission file, attaching that to a publication format and the making that directly available (no sales price, openAccess). Are you seeing this as well?

The `revision` element does not allow the `sales_type` attribute. It also seems that `setting_sales` price to 0 in `revision` element has no effect when importing.

**Comment by jonasraoni** [comment]
Hi @ajnyga!

In order to import some books, first I created a book, filled all the fields I could find, then I exported it to XML, which didn't add this `<revision>` element 🤔

But after a fast search I found a `sample.xml`, which has this element... So yeah, there's something missing here.

---

Hi @defstat! This PR is missing your review, but I've heard you were fixing such issues already, so is my PR still valid?!

If you're not working on this anymore, I might take a look, if you can confirm which format we should follow (`sample.xml` or current XML format).

**Comment by ajnyga** [comment]
It seems to me that the code tries to read those attributes straight from the `submission_file` element (https://github.com/pkp/pkp-lib/blob/main/plugins/importexport/native/filter/NativeXmlSubmissionFileFilter.inc.php#L150)

But the schema file does not allow the attribute there. So it could be that we could just change the schema file?

**Comment by jonasraoni** [comment]
@ajnyga Yes. FYI I can confirm that if you export a sample book and use the same XML format to import, it will work (I've just imported more than 1K books using this PR).
Well, let's way for an answer from @defstat before providing new fixes.

**Comment by ajnyga** [comment]
thanks, yes the memory_limit issue I was familiar with because it applies also to OJS imports. 

So just to make sure I understand correctly, you can import books and the publicationFormats and attached files are visible for the public after the import?

**Comment by asmecher** [comment]
@jonasraoni, I think the same work I sugggested [here](https://github.com/pkp/pkp-lib/issues/7143#issuecomment-1133095553) needs to be done on this issue -- better separation of multiple fixes into different commits/issues and clarity over what's already fixed in `main` vs. `stable-3_3_0`. At this point in the `stable-3_3_0` cycle we should be disrupting as little as possible, so targeted fixes only.

**Comment by jonasraoni** [comment]
Some fixes will have to be ported to `main`, if they are not fixed already, I'll check.
Also, there's a database update in the PR. So, I'll have to retest with some XMLs and drop cosmetic fixes (e.g. generates a warning, but works) from the `stable-3_3_0`.

**Comment by jonasraoni** [comment]
Just to confirm, I've rebased my local branch and the fixes are still needed, I wasn't able to import through the CLI without them.

About the database updates, the import "works" without them, but it leads to orphaned data, as the `Filter::execute()` ends up not returning anything due to this validation: https://github.com/pkp/pkp-lib/blob/main/classes/filter/Filter.inc.php#L502

**Comment by asmecher** [comment]
Thanks, @jonasraoni, could you ping Dimitris once this is ported (as needed) to `main` and all the PRs are ready for another review?

**Comment by jonasraoni** [comment]
Hi @defstat, please take a look again on the PRs, follow some notes:
- Non-essential fixes were moved to the `main` branch.
- Most of the changes were needed for OMP, I could apply some minor changes to OJS and OPS basically just received the `pkp-lib` update.

**Comment by defstat** [comment]
Thanks @jonasraoni! @asmecher just reviewed the code and it seems ok to me. There are small migration code that seems ok, and code like [that](https://github.com/pkp/omp/blob/3621f3e9a98c3019ce612545565f801f433fcc50/tools/xmllint-exclusions.txt) which I am not familiar with. Perhaps, if you have time, you may be able to take a look to them (especially the xmllint-exclusions.txt)

**Comment by asmecher** [comment]
@defstat, you mentioned that this breaks existing plugins -- can you write a little more about that?

**Comment by defstat** [comment]
@asmecher those changes don't break anything in my knowledge. 
Perhaps you are referring to [this ](https://github.com/pkp/pkp-lib/pull/7942#discussion_r884033739) which is related to another issue and a PR of my own.

**Comment by asmecher** [comment]
Thanks, @jonasraoni and @defstat; I've merged all the PRs listed above (though most manually because of submodule conflicts).
